"""Add the 2-photon-frame-aligned eye-tracking product (AllenSDK ``get_eye_tracking``).

This is a *second, complementary* eye product to the ``ophys_eye_gaze_mapping`` H5 handled by
``_eye_gaze_mapping.py``. Both derive from the same DeepLabCut eye/pupil tracking (their pupil
areas are identical up to a px^2 -> cm^2 conversion), but they are produced by different
pipelines and use different gaze coordinate conventions, so both are stored.

Provenance: these ``eye_tracking.npy`` files were generated by the
``AllenInstitute/visual-coding-saccades`` project (``data_loading/package_eye_data.py``) from
Allen LIMS raw eye-tracking + time-synchronization files, resampled to the 2-photon frames.
They are published in the versioned ``visual-coding-ophys-data`` S3 release and exposed by
``allensdk.core.brain_observatory_cache.BrainObservatoryCache.get_eye_tracking``. Present for
818 of the 1518 experiments. Each row is one 2-photon frame; columns (documented by AllenSDK
PR #2740) are ``[frame_number, eye_area_cm2, pupil_area_cm2, azimuth_deg, altitude_deg]``.

Downloaded env-free at conversion time with quilt3 (the bucket is public), read with numpy,
and attached to ``nwbfile.processing['behavior']`` under ``*_dlc`` names (distinct from the
gaze-mapping product's ``*_dlc_screen_mapping`` names and from any v1-embedded eye tracking).
The series are timestamped by the session's dF/F (2-photon) frame clock, which the frame
index column indexes.
"""
from pathlib import Path

import numpy as np
import quilt3 as q3
from pynwb.base import TimeSeries
from pynwb.behavior import CompassDirection, PupilTracking, SpatialSeries

# Versioned Allen data-release bucket (us-west-2) that backs AllenSDK get_eye_tracking.
S3_EYE_TRACKING_BUCKET = "s3://visual-coding-ophys-data"
S3_EYE_TRACKING_PREFIX = "visual-coding-ophys/behavior_ophys_experiments"

_SUFFIX = "_dlc"

# Provenance + status note appended to every C series description.
_PROVENANCE = (
    " Provenance: generated by the AllenInstitute/visual-coding-saccades project "
    "(data_loading/package_eye_data.py) from Allen LIMS raw eye-tracking + time-sync files, "
    "resampled to the 2-photon frames; published in the versioned visual-coding-ophys-data S3 "
    "release and exposed via AllenSDK BrainObservatoryCache.get_eye_tracking. Provisional: "
    "Allen flags this eye tracking as still being validated."
)


def resolve_eye_tracking_2p_key(bucket, experiment_id: int) -> str | None:
    """Return the S3 key of the eye_tracking.npy for this experiment, or ``None``.

    Lists the experiment's release folder and looks for ``eye_tracking.npy``. Returns ``None``
    when the experiment is not in the release (expected for 700 of 1518 sessions -- a normal
    no-op); raises if more than one match (must never happen).
    """
    listing = bucket.ls(f"{S3_EYE_TRACKING_PREFIX}/{experiment_id}/")
    if not listing or len(listing) < 2:
        return None
    # The release bucket is versioned, so ls returns every object version; keep only the
    # current version of eye_tracking.npy and dedupe.
    keys = {
        f["Key"] for f in listing[1]
        if f["Key"].endswith("/eye_tracking.npy") and f.get("IsLatest", True)
    }
    if len(keys) > 1:
        raise RuntimeError(
            f"Expected 0 or 1 eye_tracking.npy for experiment {experiment_id}, found {len(keys)}: {keys}"
        )
    return next(iter(keys)) if keys else None


def _dff_frame_timestamps(nwbfile) -> np.ndarray:
    """Return the session's dF/F (2-photon) frame timestamps in seconds.

    The eye_tracking.npy frame-index column indexes these frames, so they are the correct
    timestamps for its per-frame series. Raises (fail loud) if the dF/F series or its
    timestamps are missing.
    """
    ophys = nwbfile.processing.get("ophys")
    dff = ophys.data_interfaces.get("DfOverF") if ophys is not None else None
    if dff is None:
        raise RuntimeError("Cannot align eye_tracking: processing['ophys']['DfOverF'] not found.")
    roi_response_series = next(iter(dff.roi_response_series.values()))
    timestamps = roi_response_series.timestamps
    if timestamps is None:
        raise RuntimeError("Cannot align eye_tracking: DfOverF RoiResponseSeries has no timestamps.")
    return np.asarray(timestamps[:], dtype=float)


def build_eye_tracking_2p_containers(eye_tracking: np.ndarray, timestamps: np.ndarray):
    """Build the (CompassDirection, PupilTracking) containers from the (N, 5) array.

    Columns: [frame_number, eye_area_cm2, pupil_area_cm2, azimuth_deg, altitude_deg].
    """
    if eye_tracking.ndim != 2 or eye_tracking.shape[1] != 5:
        raise RuntimeError(f"Expected an (N, 5) eye_tracking array, got shape {eye_tracking.shape}.")
    if eye_tracking.shape[0] != len(timestamps):
        raise RuntimeError(
            f"eye_tracking rows {eye_tracking.shape[0]} != dF/F frame count {len(timestamps)}."
        )

    gaze = np.column_stack([eye_tracking[:, 3], eye_tracking[:, 4]])  # [azimuth, altitude] degrees
    compass_direction = CompassDirection(
        name=f"CompassDirection{_SUFFIX}",
        spatial_series=[
            SpatialSeries(
                name=f"pupil_location_spherical{_SUFFIX}",
                data=gaze,
                timestamps=timestamps,
                unit="degrees",
                reference_frame=("Angular pupil gaze direction; columns are "
                                 "[azimuth_deg, altitude_deg]."),
                description=("DeepLabCut-estimated pupil gaze direction (azimuth, altitude in "
                             "degrees), one sample per 2-photon frame." + _PROVENANCE),
            ),
        ],
    )
    pupil_tracking = PupilTracking(
        name=f"PupilTracking{_SUFFIX}",
        time_series=[
            TimeSeries(name=f"pupil_area{_SUFFIX}", data=eye_tracking[:, 2], timestamps=timestamps,
                       unit="cm^2", description="DeepLabCut-estimated pupil area (cm^2), one sample "
                       "per 2-photon frame." + _PROVENANCE),
            TimeSeries(name=f"eye_area{_SUFFIX}", data=eye_tracking[:, 1], timestamps=timestamps,
                       unit="cm^2", description="DeepLabCut-estimated eye area (cm^2), one sample "
                       "per 2-photon frame." + _PROVENANCE),
        ],
    )
    return compass_direction, pupil_tracking


def add_eye_tracking_2p(nwbfile, experiment_id: int, scratch_dir: Path) -> bool:
    """Attach the 2p-frame-aligned eye_tracking product to ``processing['behavior']``.

    Returns ``True`` if data was added, ``False`` if this experiment is not in the release
    (no-op). Raises if the ``*_dlc`` containers already exist (fail loud).
    """
    bucket = q3.Bucket(S3_EYE_TRACKING_BUCKET)
    key = resolve_eye_tracking_2p_key(bucket, experiment_id)
    if key is None:
        print(f"No 2p-aligned eye_tracking release for experiment {experiment_id}; skipping.")
        return False

    local_path = scratch_dir / f"{experiment_id}_eye_tracking.npy"
    print(f"Downloading 2p-aligned eye_tracking for experiment {experiment_id} ...")
    bucket.fetch(key, local_path.as_posix())
    eye_tracking = np.load(local_path, allow_pickle=False)
    timestamps = _dff_frame_timestamps(nwbfile)

    if "behavior" not in nwbfile.processing.keys():
        nwbfile.create_processing_module(name="behavior", description="Processed behavioral data.")
    behavior = nwbfile.processing["behavior"]
    for container_name in (f"CompassDirection{_SUFFIX}", f"PupilTracking{_SUFFIX}"):
        if container_name in behavior.data_interfaces:
            raise RuntimeError(
                f"{container_name!r} already exists in processing['behavior']; refusing to overwrite."
            )

    compass_direction, pupil_tracking = build_eye_tracking_2p_containers(eye_tracking, timestamps)
    behavior.add(compass_direction)
    behavior.add(pupil_tracking)
    print(f"  -> added 2p-aligned eye_tracking ({len(timestamps)} frames) to processing['behavior'] "
          f"as *{_SUFFIX} containers.")
    return True
