"""Add the 2-photon-frame-aligned eye-tracking product (AllenSDK ``get_eye_tracking``).

This is the single eye-tracking product stored in the converted file. When it is added, any
older v1-embedded eye tracking already present in ``processing['behavior']`` (the DANDI file's
``EyeTracking`` / ``PupilTracking`` / ``CompassDirection``) is removed, so the file carries only
this product.

Provenance: these ``eye_tracking.npy`` files were generated by the
``AllenInstitute/visual-coding-saccades`` project (``data_loading/package_eye_data.py``) from
Allen LIMS raw eye-tracking + time-synchronization files, resampled to the 2-photon frames.
They are published in the versioned ``visual-coding-ophys-data`` S3 release and exposed by
``allensdk.core.brain_observatory_cache.BrainObservatoryCache.get_eye_tracking``. Present for
818 of the 1518 experiments. Each row is one 2-photon frame; columns (documented by AllenSDK
PR #2740) are ``[frame_number, eye_area_cm2, pupil_area_cm2, azimuth_deg, altitude_deg]``.

Downloaded env-free at conversion time with quilt3 (the bucket is public), read with numpy,
and attached to ``nwbfile.processing['behavior']`` as a ``CompassDirection`` (angular gaze)
and a ``PupilTracking`` (pupil/eye area) container. Their series descriptions state the source
(the visual-coding-saccades / get_eye_tracking product) so the object is self-describing even
though it reuses the standard container names the removed v1-embedded eye tracking used. The
series are timestamped by the session's dF/F (2-photon) frame clock, which the frame index
column indexes.
"""
from pathlib import Path

import numpy as np
import quilt3 as q3
from pynwb.base import TimeSeries
from pynwb.behavior import CompassDirection, PupilTracking, SpatialSeries

# Versioned Allen data-release bucket (us-west-2) that backs AllenSDK get_eye_tracking.
S3_EYE_TRACKING_BUCKET = "s3://visual-coding-ophys-data"
S3_EYE_TRACKING_PREFIX = "visual-coding-ophys/behavior_ophys_experiments"

# Source/provenance + status note appended to every series description, so each stored object
# states where it came from (this reuses the standard container names, so the description is the
# only place the source is recorded).
_PROVENANCE = (
    " Source: the AllenSDK BrainObservatoryCache.get_eye_tracking product, generated by the "
    "AllenInstitute/visual-coding-saccades project (data_loading/package_eye_data.py) from Allen "
    "LIMS raw eye-tracking + time-synchronization files, resampled to the 2-photon frames, and "
    "published in the versioned visual-coding-ophys-data S3 release. Provisional: Allen flags "
    "this eye tracking as still being validated."
)


def resolve_eye_tracking_2p_key(bucket, experiment_id: int) -> str | None:
    """Return the S3 key of the eye_tracking.npy for this experiment, or ``None``.

    Lists the experiment's release folder and looks for ``eye_tracking.npy``. Returns ``None``
    when the experiment is not in the release (expected for 700 of 1518 sessions -- a normal
    no-op); raises if more than one match (must never happen).
    """
    listing = bucket.ls(f"{S3_EYE_TRACKING_PREFIX}/{experiment_id}/")
    if not listing or len(listing) < 2:
        return None
    # The release bucket is versioned, so ls returns every object version; keep only the
    # current version of eye_tracking.npy and dedupe.
    keys = {
        f["Key"] for f in listing[1]
        if f["Key"].endswith("/eye_tracking.npy") and f.get("IsLatest", True)
    }
    if len(keys) > 1:
        raise RuntimeError(
            f"Expected 0 or 1 eye_tracking.npy for experiment {experiment_id}, found {len(keys)}: {keys}"
        )
    return next(iter(keys)) if keys else None


def _dff_frame_timestamps(nwbfile) -> np.ndarray:
    """Return the session's dF/F (2-photon) frame timestamps in seconds.

    The eye_tracking.npy frame-index column indexes these frames, so they are the correct
    timestamps for its per-frame series. Raises (fail loud) if the dF/F series or its
    timestamps are missing.
    """
    ophys = nwbfile.processing.get("ophys")
    dff = ophys.data_interfaces.get("DfOverF") if ophys is not None else None
    if dff is None:
        raise RuntimeError("Cannot align eye_tracking: processing['ophys']['DfOverF'] not found.")
    roi_response_series = next(iter(dff.roi_response_series.values()))
    timestamps = roi_response_series.timestamps
    if timestamps is None:
        raise RuntimeError("Cannot align eye_tracking: DfOverF RoiResponseSeries has no timestamps.")
    return np.asarray(timestamps[:], dtype=float)


def build_eye_tracking_2p_containers(eye_tracking: np.ndarray, timestamps: np.ndarray):
    """Build the (CompassDirection, PupilTracking) containers from the (N, 5) array.

    Columns: [frame_number, eye_area_cm2, pupil_area_cm2, azimuth_deg, altitude_deg].
    """
    if eye_tracking.ndim != 2 or eye_tracking.shape[1] != 5:
        raise RuntimeError(f"Expected an (N, 5) eye_tracking array, got shape {eye_tracking.shape}.")
    if eye_tracking.shape[0] != len(timestamps):
        raise RuntimeError(
            f"eye_tracking rows {eye_tracking.shape[0]} != dF/F frame count {len(timestamps)}."
        )

    gaze = np.column_stack([eye_tracking[:, 3], eye_tracking[:, 4]])  # [azimuth, altitude] degrees
    compass_direction = CompassDirection(
        name="CompassDirection",
        spatial_series=[
            SpatialSeries(
                name="pupil_location_spherical",
                data=gaze,
                timestamps=timestamps,
                unit="degrees",
                reference_frame=("Angular pupil gaze direction; columns are "
                                 "[azimuth_deg, altitude_deg]."),
                description=("DeepLabCut-estimated pupil gaze direction (azimuth, altitude in "
                             "degrees), one sample per 2-photon frame." + _PROVENANCE),
            ),
        ],
    )
    pupil_tracking = PupilTracking(
        name="PupilTracking",
        time_series=[
            TimeSeries(name="pupil_area", data=eye_tracking[:, 2], timestamps=timestamps,
                       unit="cm^2", description="DeepLabCut-estimated pupil area (cm^2), one sample "
                       "per 2-photon frame." + _PROVENANCE),
            TimeSeries(name="eye_area", data=eye_tracking[:, 1], timestamps=timestamps,
                       unit="cm^2", description="DeepLabCut-estimated eye area (cm^2), one sample "
                       "per 2-photon frame." + _PROVENANCE),
        ],
    )
    return compass_direction, pupil_tracking


# The v1-embedded eye tracking already present in the DANDI file's processing['behavior'];
# removed when this product is added so the file carries a single eye-tracking product.
_V1_EMBEDDED_EYE_CONTAINERS = ("EyeTracking", "PupilTracking", "CompassDirection")


def _remove_v1_embedded_eye_tracking(behavior) -> None:
    """Remove the DANDI file's v1-embedded EyeTracking/PupilTracking/CompassDirection, if present."""
    for name in _V1_EMBEDDED_EYE_CONTAINERS:
        if name in behavior.data_interfaces:
            behavior.data_interfaces.pop(name)
            print(f"  -> removed v1-embedded {name} from processing['behavior'].")


def add_eye_tracking_2p(nwbfile, experiment_id: int, scratch_dir: Path) -> bool:
    """Attach the 2p-frame-aligned eye_tracking product to ``processing['behavior']``.

    The stored containers reuse the standard names ``CompassDirection`` and ``PupilTracking``;
    the file's v1-embedded eye tracking (``EyeTracking`` / ``PupilTracking`` / ``CompassDirection``)
    is removed first so those names are free and only this product remains (its series
    descriptions state the source). Returns ``True`` if data was added, ``False`` if this
    experiment is not in the release (no-op; the v1-embedded eye tracking, if any, is left
    untouched). Raises if a ``CompassDirection``/``PupilTracking`` container unexpectedly remains
    after the v1-embedded removal.
    """
    bucket = q3.Bucket(S3_EYE_TRACKING_BUCKET)
    key = resolve_eye_tracking_2p_key(bucket, experiment_id)
    if key is None:
        print(f"No 2p-aligned eye_tracking release for experiment {experiment_id}; skipping.")
        return False

    local_path = scratch_dir / f"{experiment_id}_eye_tracking.npy"
    print(f"Downloading 2p-aligned eye_tracking for experiment {experiment_id} ...")
    bucket.fetch(key, local_path.as_posix())
    eye_tracking = np.load(local_path, allow_pickle=False)
    timestamps = _dff_frame_timestamps(nwbfile)

    if "behavior" not in nwbfile.processing.keys():
        nwbfile.create_processing_module(name="behavior", description="Processed behavioral data.")
    behavior = nwbfile.processing["behavior"]

    # This product uses the standard container names, so first drop the v1-embedded eye tracking
    # (EyeTracking/PupilTracking/CompassDirection) the DANDI file may carry, then confirm the
    # names are free before adding.
    _remove_v1_embedded_eye_tracking(behavior)
    for container_name in ("CompassDirection", "PupilTracking"):
        if container_name in behavior.data_interfaces:
            raise RuntimeError(
                f"{container_name!r} still present in processing['behavior'] after removing the "
                f"v1-embedded eye tracking; refusing to overwrite."
            )

    compass_direction, pupil_tracking = build_eye_tracking_2p_containers(eye_tracking, timestamps)
    behavior.add(compass_direction)
    behavior.add(pupil_tracking)
    print(f"  -> added eye_tracking ({len(timestamps)} frames) to processing['behavior'] as "
          f"CompassDirection + PupilTracking.")
    return True
